
import Head from "next/head";
import Image from "next/image";
import Header from "./../components/Header";
import Callout from "./../components/callout";
import styles from "./../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sakari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Callout />
      <footer className={styles.footer}>Have not done the mobile views.  Callouts, Footer etc down here</footer>
    </>
  );
}